export const AUTH_ERROR = {
    USER_EXIST_USERNAME: 'USER_EXIST_USERNAME',
    USER_EXIST_EMAIL: 'USER_EXIST_EMAIL',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_INPUT_FAILED: 'USER_INPUT_FAILED',
};

export const PROJECT_ERROR = {
    PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
    PROJECT_NOT_EXIST_TEAM: 'PROJECT_NOT_EXIST_TEAM',
};
